version: '3.3'
services:
  # server:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #     args:
  #       - http_proxy
  #       - https_proxy
  #       - no_proxy
  #   image: inari/server:latest
  #   ports:
  #     - '8081:8081'
  #   stdin_open: true
  #   tty: true
  postgres:
    image: postgres:9.6.1
    ports:
      - '5435:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: inari
      POSTGRES_PASSWORD: inari
      POSTGRES_DB: inari
  postgres_test:
    image: postgres:9.6.1
    ports:
      - '5436:5432'
    volumes:
      - ./postgres-data-test:/var/lib/postgresql
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
