export enum AnimeFilterEnum {
  GENRE = "GENRE",
  EXCLUDE_GENRE = "EXCLUDE_GENRE",
  TYPE_ANIME = "TYPE_ANIME",
  STATUS_ANIME = "STATUS_ANIME",
  SEASON = "SEASON",
  YEARS = "YEARS",
  SEARCH = "SEARCH"
}
